#!/usr/bin/bash

./gradlew dist --no-daemon -q

if [[ ! $? == '0' ]]; then
    echo "Build Failed"
    exit 1
fi

cp  ./build/libs/previewer.jar ../Botzilla/map-previewer.jar

scp ./build/libs/previewer.jar nydus6:/root/map-previewer.jar
ssh nydus6 cp /root/map-previewer.jar /root/Botzilla/map-previewer.jar
ssh nydus6 rm /root/map-previewer.jar
